/*
 * Filename: sc_speed_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Any speed data type
 * name: sc_speed
 * shortname: speed
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_speed_type.h"
#include "led.h" 


/* USER CODE START SC_SPEED_INCLUDE */

/* USER CODE END SC_SPEED_INCLUDE */




/* USER CODE START SC_SPEED_USERDEFINITIONS */

/* USER CODE END SC_SPEED_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_SPEED signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_SPEED_driverOut(const SC_SPEED_data_t  *const data)
{
	/* USER CODE START driverOutSC_SPEED */
    if (data->speed >0)
    {
	//Scale application data to drive format
    uint8_t green_channel = data->speed;

	//Write scaled data to driver
    LED_red_Write(0);
    LED_RGB_Set(0,green_channel,0);
    }
    else
    {
        LED_red_Write(1);
    }
	return RC_SUCCESS;
	/* USER CODE END driverOutSC_SPEED */
}



