
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: The common signal pool, all signals will be stored here
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */

/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_joystick.h"
#include "sc_speed.h"
#include "sc_speed.h"
#include "sc_speed.h"



/*
 * description: joystick signal to control the car
 * indriver: default
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_joystick_onData
 * outdriver: 0
 * resource: None
 * shortname: joystick
 * signalclass: sc_joystick
 * signalpool: sp_common
 */
extern SC_JOYSTICK_t SO_JOYSTICK_signal;


/*
 * description: Speed signal defined by the Control SWC
 * indriver: 0
 * name: so_speed
 * onDataError: 0
 * onDataUpdate: ev_speed_onData
 * outdriver: 0
 * resource: None
 * shortname: speed
 * signalclass: sc_speed
 * signalpool: sp_common
 */
extern SC_SPEED_t SO_SPEED_signal;


/*
 * description: signal value written to the engine
 * indriver: 0
 * name: so_enginesignal
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: enginesignal
 * signalclass: sc_speed
 * signalpool: sp_common
 */
extern SC_SPEED_t SO_ENGINESIGNAL_signal;


/*
 * description: signal value written to the Brakelight
 * indriver: 0
 * name: so_brakeLight
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: brakeLight
 * signalclass: sc_speed
 * signalpool: sp_common
 */
extern SC_SPEED_t SO_BRAKELIGHT_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common();

#endif