/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/

    #if (0 > 0) && 0
    #if 0
    #define ISR_1_RES   1
    #else
    #define ISR_1_RES   0
    #endif
    #define ISR_1_CAT   1
    #else
    #define ISR_1_RES   0
    #define ISR_1_CAT   0
    #endif

    #if (0 > 1) && 0
    #if 0
    #define ISR_2_RES   1
    #else
    #define ISR_2_RES   0
    #endif
    #define ISR_2_CAT   1
    #else
    #define ISR_2_RES   0
    #define ISR_2_CAT   0
    #endif

    #if (0 > 2) && 0
    #if 0
    #define ISR_3_RES   1
    #else
    #define ISR_3_RES   0
    #endif
    #define ISR_3_CAT   1
    #else
    #define ISR_3_RES   0
    #define ISR_3_CAT   0
    #endif
    
    #if (0 > 3) && 0
    #if 0
    #define ISR_4_RES   1
    #else
    #define ISR_4_RES   0
    #endif
    #define ISR_4_CAT   1
    #else
    #define ISR_4_RES   0
    #define ISR_4_CAT   0
    #endif

    #if (0 > 4) && 0
    #if 0
    #define ISR_5_RES   1
    #else
    #define ISR_5_RES   0
    #endif
    #define ISR_5_CAT   1
    #else
    #define ISR_5_RES   0
    #define ISR_5_CAT   0
    #endif

    #if (0 > 5) && 0
    #if 0
    #define ISR_6_RES   1
    #else
    #define ISR_6_RES   0
    #endif
    #define ISR_6_CAT   1
    #else
    #define ISR_6_RES   0
    #define ISR_6_CAT   0
    #endif

    #if (0 > 6) && 0
    #if 0
    #define ISR_7_RES   1
    #else
    #define ISR_7_RES   0
    #endif
    #define ISR_7_CAT   1
    #else
    #define ISR_7_RES   0
    #define ISR_7_CAT   0
    #endif

    #if (0 > 7) && 0
    #if 0
    #define ISR_8_RES   1
    #else
    #define ISR_8_RES   0
    #endif
    #define ISR_8_CAT   1
    #else
    #define ISR_8_RES   0
    #define ISR_8_CAT   0
    #endif

    #if (0 > 8) && 0
    #if 0
    #define ISR_9_RES   1
    #else
    #define ISR_9_RES   0
    #endif
    #define ISR_9_CAT   1
    #else
    #define ISR_9_RES   0
    #define ISR_9_CAT   0
    #endif

    #if (0 > 9) && 0
    #if 0
    #define ISR_10_RES   1
    #else
    #define ISR_10_RES   0
    #endif
    #define ISR_10_CAT   1
    #else
    #define ISR_10_RES   0
    #define ISR_10_CAT   0
    #endif

    #if (0 > 10) && 0
    #if 0
    #define ISR_11_RES   1
    #else
    #define ISR_11_RES   0
    #endif
    #define ISR_11_CAT   1
    #else
    #define ISR_11_RES   0
    #define ISR_11_CAT   0
    #endif

    #if (0 > 11) && 0
    #if 0
    #define ISR_12_RES   1
    #else
    #define ISR_12_RES   0
    #endif
    #define ISR_12_CAT   1
    #else
    #define ISR_12_RES   0
    #define ISR_12_CAT   0
    #endif

    #if (0 > 12) && 0
    #if 0
    #define ISR_13_RES   1
    #else
    #define ISR_13_RES   0
    #endif
    #define ISR_13_CAT   1
    #else
    #define ISR_13_RES   0
    #define ISR_13_CAT   0
    #endif

    #if (0 > 13) && 0
    #if 0
    #define ISR_14_RES   1
    #else
    #define ISR_14_RES   0
    #endif
    #define ISR_14_CAT   1
    #else
    #define ISR_14_RES   0
    #define ISR_14_CAT   0
    #endif

    #if (0 > 14) && 0
    #if 0
    #define ISR_15_RES   1
    #else
    #define ISR_15_RES   0
    #endif
    #define ISR_15_CAT   1
    #else
    #define ISR_15_RES   0
    #define ISR_15_CAT   0
    #endif
    
    #if (0 > 15) && 0
    #if 0
    #define ISR_16_RES   1
    #else
    #define ISR_16_RES   0
    #endif
    #define ISR_16_CAT   1
    #else
    #define ISR_16_RES   0
    #define ISR_16_CAT   0
    #endif

    #define Number_ISR2 (ISR_1_CAT + ISR_2_CAT + ISR_3_CAT + ISR_4_CAT + ISR_5_CAT + ISR_6_CAT + ISR_7_CAT + ISR_8_CAT + ISR_9_CAT + ISR_10_CAT + ISR_11_CAT + ISR_12_CAT + ISR_13_CAT + ISR_14_CAT + ISR_15_CAT + ISR_16_CAT)
    #define Number_ISR2_Resources (ISR_1_RES + ISR_2_RES + ISR_3_RES + ISR_4_RES + ISR_5_RES + ISR_6_RES + ISR_7_RES + ISR_8_RES + ISR_9_RES + ISR_10_RES + ISR_11_RES + ISR_12_RES + ISR_13_RES + ISR_14_RES + ISR_15_RES + ISR_16_RES)

/* [] END OF FILE */
