/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
#ifndef TSK_PRIORITIES
#define TSK_PRIORITIES

#if (1 == 0x1)
#define TSK1_PRI 0U
#elif (1 == 0x2)
#define TSK1_PRI 1U
#elif (1 == 0x4)
#define TSK1_PRI 2U
#elif (1 == 0x8)
#define TSK1_PRI 3U
#elif (1 == 0x10)
#define TSK1_PRI 4U
#elif (1 == 0x20)
#define TSK1_PRI 5U
#elif (1 == 0x40)
#define TSK1_PRI 6U
#elif (1 == 0x80)
#define TSK1_PRI 7U
#endif

#if (1 == 0x1)
#define TSK2_PRI 0U
#elif (1 == 0x2)
#define TSK2_PRI 1U
#elif (1 == 0x4)
#define TSK2_PRI 2U
#elif (1 == 0x8)
#define TSK2_PRI 3U
#elif (1 == 0x10)
#define TSK2_PRI 4U
#elif (1 == 0x20)
#define TSK2_PRI 5U
#elif (1 == 0x40)
#define TSK2_PRI 6U
#elif (1 == 0x80)
#define TSK2_PRI 7U
#endif

#if (16 == 0x1)
#define TSK3_PRI 0U
#elif (16 == 0x2)
#define TSK3_PRI 1U
#elif (16 == 0x4)
#define TSK3_PRI 2U
#elif (16 == 0x8)
#define TSK3_PRI 3U
#elif (16 == 0x10)
#define TSK3_PRI 4U
#elif (16 == 0x20)
#define TSK3_PRI 5U
#elif (16 == 0x40)
#define TSK3_PRI 6U
#elif (16 == 0x80)
#define TSK3_PRI 7U
#endif

#if (4 == 0x1)
#define TSK4_PRI 0U
#elif (4 == 0x2)
#define TSK4_PRI 1U
#elif (4 == 0x4)
#define TSK4_PRI 2U
#elif (4 == 0x8)
#define TSK4_PRI 3U
#elif (4 == 0x10)
#define TSK4_PRI 4U
#elif (4 == 0x20)
#define TSK4_PRI 5U
#elif (4 == 0x40)
#define TSK4_PRI 6U
#elif (4 == 0x80)
#define TSK4_PRI 7U
#endif

#if (4 == 0x1)
#define TSK5_PRI 0U
#elif (4 == 0x2)
#define TSK5_PRI 1U
#elif (4 == 0x4)
#define TSK5_PRI 2U
#elif (4 == 0x8)
#define TSK5_PRI 3U
#elif (4 == 0x10)
#define TSK5_PRI 4U
#elif (4 == 0x20)
#define TSK5_PRI 5U
#elif (4 == 0x40)
#define TSK5_PRI 6U
#elif (4 == 0x80)
#define TSK5_PRI 7U
#endif

#if (0 == 0x1)
#define TSK6_PRI 0U
#elif (0 == 0x2)
#define TSK6_PRI 1U
#elif (0 == 0x4)
#define TSK6_PRI 2U
#elif (0 == 0x8)
#define TSK6_PRI 3U
#elif (0 == 0x10)
#define TSK6_PRI 4U
#elif (0 == 0x20)
#define TSK6_PRI 5U
#elif (0 == 0x40)
#define TSK6_PRI 6U
#elif (0 == 0x80)
#define TSK6_PRI 7U
#endif

#if (0 == 0x1)
#define TSK7_PRI 0U
#elif (0 == 0x2)
#define TSK7_PRI 1U
#elif (0 == 0x4)
#define TSK7_PRI 2U
#elif (0 == 0x8)
#define TSK7_PRI 3U
#elif (0 == 0x10)
#define TSK7_PRI 4U
#elif (0 == 0x20)
#define TSK7_PRI 5U
#elif (0 == 0x40)
#define TSK7_PRI 6U
#elif (0 == 0x80)
#define TSK7_PRI 7U
#endif

#if (0 == 0x1)
#define TSK8_PRI 0U
#elif (0 == 0x2)
#define TSK8_PRI 1U
#elif (0 == 0x4)
#define TSK8_PRI 2U
#elif (0 == 0x8)
#define TSK8_PRI 3U
#elif (0 == 0x10)
#define TSK8_PRI 4U
#elif (0 == 0x20)
#define TSK8_PRI 5U
#elif (0 == 0x40)
#define TSK8_PRI 6U
#elif (0 == 0x80)
#define TSK8_PRI 7U
#endif

#endif
/* [] END OF FILE */
