/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "JOYSTICK_X_aliases.h"
#include "JOYSTICK_X.h"
#include "JOYSTICK_Y_aliases.h"
#include "JOYSTICK_Y.h"
#include "JOYSTICK_ADC_XY.h"
#include "LED_red_aliases.h"
#include "LED_red.h"
#include "LED_yellow_aliases.h"
#include "LED_yellow.h"
#include "LED_green_aliases.h"
#include "LED_green.h"
#include "RGB_PWM_red.h"
#include "PWM_Clock.h"
#include "RGB_PWM_green.h"
#include "RGB_PWM_blue.h"
#include "RGB_R_aliases.h"
#include "RGB_R.h"
#include "RGB_G_aliases.h"
#include "RGB_G.h"
#include "RGB_B_aliases.h"
#include "RGB_B.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "UART_LOG.h"
#include "WD_Button_aliases.h"
#include "WD_Button.h"
#include "isr_Button.h"
#include "JOYSTICK_ADC_XY_SAR.h"
#include "JOYSTICK_ADC_XY_IntClock.h"
#include "JOYSTICK_ADC_XY_TempBuf_dma.h"
#include "JOYSTICK_ADC_XY_FinalBuf_dma.h"
#include "JOYSTICK_ADC_XY_IRQ.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

