/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
    #define EE_MAX_EVENT `@Number_of_Events`
    #if `@Number_of_Events` > 0
    #define `@Event_1` 0x1U
    #endif
    #if `@Number_of_Events` > 1
    #define `@Event_2` 0x2U
    #endif
    #if `@Number_of_Events` > 2
    #define `@Event_3` 0x4U
    #endif
    #if `@Number_of_Events` > 3
    #define `@Event_4` 0x8U
    #endif
    #if `@Number_of_Events` > 4
    #define `@Event_5` 0x10U
    #endif
    #if `@Number_of_Events` > 5
    #define `@Event_6` 0x20U
    #endif
    #if `@Number_of_Events` > 6
    #define `@Event_7` 0x40U
    #endif
    #if `@Number_of_Events` > 7
    #define `@Event_8` 0x80U
    #endif
    #if `@Number_of_Events` > 8
    #define `@Event_9` 0x100U
    #endif
    #if `@Number_of_Events` > 9
    #define `@Event_10` 0x200U
    #endif
    #if `@Number_of_Events` > 10
    #define `@Event_11` 0x400U
    #endif
    #if `@Number_of_Events` > 11
    #define `@Event_12` 0x800U
    #endif
    #if `@Number_of_Events` > 12
    #define `@Event_13` 0x1000U
    #endif
    #if `@Number_of_Events` > 13
    #define `@Event_14` 0x2000U
    #endif
    #if `@Number_of_Events` > 14
    #define `@Event_15` 0x4000U
    #endif
    #if `@Number_of_Events` > 15
    #define `@Event_16` 0x8000U
    #endif
    #if `@Number_of_Events` > 16
    #define `@Event_17` 0x10000U
    #endif
    #if `@Number_of_Events` > 17
    #define `@Event_18` 0x20000U
    #endif
    #if `@Number_of_Events` > 18
    #define `@Event_19` 0x40000U
    #endif
    #if `@Number_of_Events` > 19
    #define `@Event_20` 0x80000U
    #endif
    #if `@Number_of_Events` > 20
    #define `@Event_21` 0x100000U
    #endif
    #if `@Number_of_Events` > 21
    #define `@Event_22` 0x200000U
    #endif
    #if `@Number_of_Events` > 22
    #define `@Event_23` 0x400000U
    #endif
    #if `@Number_of_Events` > 23
    #define `@Event_24` 0x800000U
    #endif
    #if `@Number_of_Events` > 24
    #define `@Event_25` 0x1000000U
    #endif
    #if `@Number_of_Events` > 25
    #define `@Event_26` 0x2000000U
    #endif
    #if `@Number_of_Events` > 26
    #define `@Event_27` 0x4000000U
    #endif
    #if `@Number_of_Events` > 27
    #define `@Event_28` 0x8000000U
    #endif
    #if `@Number_of_Events` > 28
    #define `@Event_29` 0x10000000U
    #endif
    #if `@Number_of_Events` > 29
    #define `@Event_30` 0x20000000U
    #endif
    #if `@Number_of_Events` > 30
    #define `@Event_31` 0x40000000U
    #endif

/* [] END OF FILE */
