/*
 * Filename: swc_remote.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: This SWC will read the value from the Joystick and send the value via so_joystick
 * name: swc_remote
 * shortname: remote
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_remote.h"
#include "WatchDogTimer.h" //Including WDT header file


/* USER CODE START SWC_REMOTE_INCLUDE */

/* USER CODE END SWC_REMOTE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_REMOTE_USERDEFINITIONS */

/* USER CODE END SWC_REMOTE_USERDEFINITIONS */



/*
 * component: swc_remote
 * cycletime: 10
 * description: Runnable which will read the joystick value from the driver
 * events: 
 * name: REMOTE_readJoystick_run
 * shortname: readJoystick
 * signalIN: 
 * signalOUT: so_joystick
 * task: tsk_io
 */

/** Beginning of the Flow **/

//This runnable will read the value from the joystick using Pullport API and send it to the so_joystick signal

void REMOTE_readJoystick_run(RTE_event ev)
{
	
	/* USER CODE START REMOTE_readJoystick_run */
    
    //Reading the Driver data via the push pull API and putting it to SO_Joystick signal
    RC_t result = RTE_SC_JOYSTICK_pullPort(&SO_JOYSTICK_signal);
    
    //Error Handling of SO_Joystick Signal
    if (result != RC_SUCCESS)
    {
        //Pullport failed
        UART_LOG_PutString("\nFailure: Joystick driver value not updated on SO_JOYSTICK_signal");     

    }
/*  else
    {
        //Pullport passed
        UART_LOG_PutString("\nFailure: Joystick driver value updated on SO_JOYSTICK_signal");
    }*/
    
    //Delay to check WD Functionality
    //CyDelay(5000);
    WD_Alive(run_remote_pos);
    
    /* USER CODE END REMOTE_readJoystick_run */
}

/* USER CODE START SWC_REMOTE_FUNCTIONS */

/* USER CODE END SWC_REMOTE_FUNCTIONS */

