
/*
 * Filename: swc_brakelight.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Based on the value present on so_speed, this component will interact with the brakelights
 */

#ifndef _H_DEFINE_SWC_BRAKELIGHT
#define _H_DEFINE_SWC_BRAKELIGHT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_BRAKELIGHT_INCLUDES */

/* USER CODE END SWC_BRAKELIGHT_INCLUDES */



/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */


/*
 * component: swc_BrakeLight
 * cycletime: 0
 * description: Runnable which will access the brake light depending on the value in the so_signal
 * events: ev_speed_onData
 * name: BRAKELIGHT_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: so_speed
 * signalOUT: so_brakeLight
 * task: tsk_brakelight
 */
void BRAKELIGHT_setBrakeLight_run(RTE_event ev);


#endif