/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: This component will read the joystick value and do the necessary computation and will update the value on the so_speed
 * name: swc_control
 * shortname: control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"
#include "WatchDogTimer.h" //Including WDT header file

/* USER CODE START SWC_CONTROL_INCLUDE */

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
 * component: swc_control
 * cycletime: 0
 * description: Runnable depending on the joystick value will control the speed
 * events: ev_joystick_onData
 * name: CONTROL_calcControl_run
 * shortname: calcControl
 * signalIN: so_joystick
 * signalOUT: so_speed
 * task: tsk_control
 */
void CONTROL_calcControl_run(RTE_event ev){
    
    /* USER CODE START CONTROL_calcControl_run */
    //Giving Initial value of speed as 0
    SC_SPEED_data_t speedValue = SC_SPEED_INIT_DATA;
    RC_t ret = RC_SUCCESS; 
    
    //Reading the value from the SO_JOYSTICK
    if (RTE_SC_JOYSTICK_get(&SO_JOYSTICK_signal).joystick_y > 0)
    {
        //Dummy code to check if the reading is successful
        //UART_LOG_PutString("\nSuccessful Read of the data from SO_JOYSTICK ");
        //Conversion of Joystick value to speed value
        //If the Joystick value >0 , speed = 2 * Joystick value 
        speedValue.speed = 2*(RTE_SC_JOYSTICK_get(&SO_JOYSTICK_signal).joystick_y) ;
    }
    else
    {
        //Dummy code to check if the reading is unsuccessful
        UART_LOG_PutString("\nUnsuccessful Read of the data from SO_JOYSTICK ");
        //else less than or equal to 0, speed = 0
        speedValue.speed = 0;
    }
    
    //Updating speed object with the speed value:
    
    ret = RTE_SC_SPEED_set(&SO_SPEED_signal,speedValue);
    //if result is successful then put in UART_LOG_Putstring: result is successful else not
    if (ret==RC_SUCCESS)
    {
        //UART_LOG_PutString("\nSpeed Object update successful");   
    }
    else
    {
        UART_LOG_PutString("\nSpeed Object update unsuccessful");
    }
    WD_Alive(run_calcControl_pos);
    /* USER CODE END CONTROL_calcControl_run */
}

/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

