/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Based on the value present on so_speed, this component will interact with the Engine via PWM signal
 * name: swc_Engine
 * shortname: Engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"
#include "WatchDogTimer.h" //Including WDT header file


/* USER CODE START SWC_ENGINE_INCLUDE */

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
 * component: swc_Engine
 * cycletime: 100
 * description: Runnable which will control the Engine
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_speed
 * signalOUT: so_enginesignal
 * task: tsk_io
 */
void ENGINE_setEngine_run(RTE_event ev){
	
	/* USER CODE START ENGINE_setEngine_run */
    
    //Giving Initial value of enginee speed as 0
    SC_SPEED_data_t enginespeedvalue = SC_SPEED_INIT_DATA;
    RC_t res = RC_SUCCESS;
    
    //Checking the age of speed signal and if signal is not too old then update the engine speed with speed signal value
    
    if(RTE_SC_SPEED_getAge(&SO_SPEED_signal) <10)
    {
        //Checking if the signal is not too old :
        //UART_LOG_PutString("\nSpeed signal is not old");
        
        enginespeedvalue.speed = RTE_SC_SPEED_get(&SO_SPEED_signal).speed;
        //Printing on UART :
        UART_LOG_PutString("\nEngine signal updated with value of speed signal");
    }
    else
    {
        //Checking if the signal is old :
        UART_LOG_PutString("\nSpeed signal is old");
        //If signal is old, then update engine speed value = 0
        enginespeedvalue.speed = 0;
        UART_LOG_PutString("\nEngine signal updated with value of 0");
    }
    
    //Now, updating the enginee speed object with the value in the enginee speed value
    
    res = RTE_SC_SPEED_set(&SO_ENGINESIGNAL_signal, enginespeedvalue);
    
    if (res == RC_SUCCESS)
    {
        UART_LOG_PutString("\nEnginee signal object updated with engine signal value");
        //Writing the enginee signal object to the PWM driver using Push port API
        res = RTE_SC_SPEED_pushPort(&SO_ENGINESIGNAL_signal);
        //Error Handling
        if (res != RC_SUCCESS)
        {
            UART_LOG_PutString("\nError: Enginee signal not able to write to Driver");
        }
/*        else
        {
            UART_LOG_PutString("\nEnginee signal written to Driver");
        }*/
    }
    else
    {
        UART_LOG_PutString("\nERROR: Enginee signal object not updated with engine signal value");
    }

    WD_Alive(run_engine_pos);
    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

