/*
 * Filename: tsk_brakelight.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Task deal with the working of the brake light
 * events: ev_speed_onData
 * mode: Cyclic and Event
 * name: tsk_brakelight
 * shortname: brakelight
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 1
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_brakelight.h"



/* USER CODE START TSK_BRAKELIGHT_INCLUDE */

/* USER CODE END TSK_BRAKELIGHT_INCLUDE */

#include "swc_brakelight.h"



/* USER CODE START TSK_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END TSK_BRAKELIGHT_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable_tsk_brakelight[] = {
};
const uint16_t RTE_cyclicActivation_tsk_brakelight_size = sizeof (RTE_cyclicActivationTable_tsk_brakelight) / sizeof(RTE_cyclicTable_t); 

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_brakelight[] = {
    { BRAKELIGHT_setBrakeLight_run, ev_speed_onData },  //Runnable which will access the brake light depending on the value in the so_signal
}; 
const uint16_t RTE_eventActivation_tsk_brakelight_size = sizeof (RTE_eventActivationTable_tsk_brakelight) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Task deal with the working of the brake light
 * events: ev_speed_onData
 * mode: Cyclic and Event
 * name: tsk_brakelight
 * shortname: brakelight
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 1
 */
TASK(tsk_brakelight)
{
	/* ticktime of the task */
	uint32_t ticktime = 0;
	
    EventMaskType ev = 0;
	
	/* USER CODE START TSK_BRAKELIGHT_INIT */

	/* USER CODE END TSK_BRAKELIGHT_INIT */
    
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_speed_onData);
        GetEvent(tsk_brakelight,&ev);
        ClearEvent(ev);
    
		/* USER CODE START TSK_BRAKELIGHT_TASKBOBY_PRE */

		/* USER CODE END TSK_BRAKELIGHT_TASKBODY_PRE */
        
        if (ev & 0){
            //Process Cyclic table on tick
            RTE_ProcessCyclicTable(RTE_cyclicActivationTable_tsk_brakelight, RTE_cyclicActivation_tsk_brakelight_size, ticktime);

			ticktime += 1;
			if (ticktime > 0xFFFFFF00) ticktime = 0;

		};
		
		//Process data driven events
		RTE_ProcessEventTable(RTE_eventActivationTable_tsk_brakelight, RTE_eventActivation_tsk_brakelight_size, ev);
		
		/* USER CODE START TSK_BRAKELIGHT_TASKBODY_POST */

		/* USER CODE END TSK_BRAKELIGHT_TASKBODY_POST */
        
    }
	
	//Just in Case
	TerminateTask();
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_BRAKELIGHT_ISR */

/* USER CODE END TSK_BRAKELIGHT_ISR */

